### ISSUE TITLE
[help wanted] service-worker file is not server from top level 

### ISSUE THREAD

**Issue by Andarist** [goldhand/sw-precache-webpack-plugin#1]
Hey,

my problem is probably cause of my lack of knowledge of the topic, but I'm struggling with it since yesterday and thought I might ask for a help eventually ;)

I use pretty standard configs, however I cannot force webpack to serve generated service worker at top level of my app during development. In normal case I would just add new `entry` to the webpack configuration, but here I have no entry point for a `service-worker` file as it is generated from the scratch by a plugin. Is there any option to allow that now? 

my `webpack.config.js` (important parts)
```
const SWPrechaceConfig = require('./sw-precache-config')
const config = {
	context: __dirname,
	entry: {
		app: ['./src/app/index'],
	},
	output: {
		path: path.resolve(__dirname, './dist'),
		filename: '[name].js',
	},
	resolve: {
		extensions: ['', '.es6', '.js', '.json'],
	},
	module: {
		preLoaders: [
			{test: /\.jsx?$/, loader: 'eslint', exclude: /node_modules/},
		],
		loaders: [
			{test: /\.jsx?$/, loaders: ['react-hot', 'babel'], exclude: /node_modules/},
			{test: /\.html$/, loader: 'raw'},
			{test: /\.css$/, loader: 'css'},
			{test: /\.styl$/, loader: 'style!css!postcss!stylus'},
			{test: /\.json$/, loader: 'json'},
			{test: /\.svg$/, loader: 'babel!svg-react'},
		],
	},
	plugins: [new SWPrecacheWebpackPlugin(SWPrechaceConfig)],
}
```

and my `SWPrechaceConfig`:
```
module.exports = {
	cacheId: "local_app",
	maximumFileSizeToCacheInBytes: 4194304,
	runtimeCaching: [{
		handler: "cacheFirst",
		urlPattern: /[.]mp3$/,
	}],
	staticFileGlobs: [
		"dist/app.js"
	],
	stripPrefix: "dist/",
	verbose: true,
}
```

**Comment by goldhand** [comment]
@Andarist I if you want to pass a set of sw-precache options into the plugin you just need to add it as an `options` key:
```javascript
const SWPrechaceConfig = require('./sw-precache-config');

const config = {
    ...
    },
    plugins: [
        new SWPrecacheWebpackPlugin(
            {
                options: SWPrechaceConfig,
            }
        )
    ],
}
```

**Comment by goldhand** [comment]
Also currently the output path is going to be `compiler.options.output.path`. In your situation, that would put the file here: `path.resolve(__dirname, './dist')` as specified in your `output` in your config.

I will update and allow you to just pass SWPrecacheConfig, the way you are using it, that makes more sense than having the `options` requirement.

**Comment by goldhand** [comment]
And the plugin will automatically determine the files to cache based on your bundles being built if you omit the `staticFileGlobs` argument.

**Comment by Andarist** [comment]
Hah, I even didn't realize it wasn't using my custom config cause I was focused on not being able to serve it through localhost.

My problem was (and still is) that I don't know how to serve generated output file (which is generated at path I wanted - which is `/dist`). I can access my `localhost:3070/app.js` but cannot access `localhost:3070/service-worker.js` without adding second `entry` in webpack's main configuration, but such solution is wrong, cause it needs to have `service-worker.js` generated first before running webpack and I would like to have it done dynamically.

**Comment by goldhand** [comment]
So this shouldn't be an entry point, the service worker is generated after the build because it needs the bundled files in order to build. 
This file should be added to your `dist/` folder after the build is done (which it sounds like it is).

Are `app.js` and `service-worker.js` in the same folder?

Also did you add:
```html
<script>
navigator.serviceWorker.register('/service-worker.js');
</script>
```
to your `index.html` file somewhere?

**Comment by Andarist** [comment]
`This file should be added to your dist/ folder after the build is done (which it sounds like it is).`

Yes, it is.

`Are app.js and service-worker.js in the same folder?`

Yes, they are.

```
Also did you add:

<script>
navigator.serviceWorker.register('/service-worker.js');
</script>
to your index.html file somewhere?
```

Yes, although I'm calling it from my js files, not html - which shouldn't make any difference.

Could you maybe make an example available on github in this repo? It would be really appreciated to see if we are even on the same page.

**Comment by goldhand** [comment]
@Andarist here you go: https://github.com/goldhand/sw-precache-webpack-plugin/tree/master/examples

**Comment by Andarist** [comment]
Ok, I know what's the difference between our setups :P You are using vanilla express here and I have WebpackDevServer configured

**Comment by goldhand** [comment]
Yeah, Webpack dev server won't work with this because it is serving bundles from memory.  I should note that in the docs.  Would be cool to figure out a way to get it to work nicely with HMR too.
