### ISSUE TITLE
should the generated service-worker.js file also be cached by service worker? 

### ISSUE THREAD

**Issue by jasan-s** [goldhand/sw-precache-webpack-plugin#10]
if so, how would i achieve that?

**Comment by goldhand** [comment]
Eh I don't think you want that. The generated service worker determines if a file should be cached again (when it has changed) and needs to be able to write over the last service worker to update. Good question though.

**Comment by jasan-s** [comment]
Oh , that makes total sense

**Comment by jasan-s** [comment]
@goldhand  can you suggest any demo that can help me understand runtime caching option. I am a bit unclear as to how to configure runtime caching option for my SPA so that I can have service worker control calls made to Firebase database for data and cache the previously downloaded dynamic data beacuse currently on refresh the data disappers(when no network)  . Any help would be greatly appreciated. 

I don't know if its better to use something like redux-persist which saves the last state in memory so state persists through refresh. but the problem with that is if there is a change in data, how would i know?
