### ISSUE TITLE
Should gzip files be ignored using staticFileGlobsIgnorePatterns property?

### ISSUE THREAD

**Issue by martosoler** [goldhand/sw-precache-webpack-plugin#100]
* [ ] **I'm submitting a bug report**
* [ ] **I'm submitting a feature request**
* [X] **I'm submitting a support request**

**webpack version:**
2.6.1

**sw-precache-webpack-plugin version**:
0.9.1

**Please tell us about your environment:**
OSX 10.12.5

**Browser:** [Chrome]

**Current behavior:**
The service-worker.js file is generated containing among other things the following files in the cache:

`
    ['/static/css/app.087c2ab96ae39bbe9b78f2c3bb840328.css', '8e020d7c181fa7c866b72fa1db89a60a'],
    ['/static/css/app.087c2ab96ae39bbe9b78f2c3bb840328.css.gz', '28e79db6375ef4d1bd36b62e092349fd'],
`

**Expected/desired behavior:**
I would like to know if that is correct or if I should just ignore all the **.gz** files using the **staticFileGlobsIgnorePatterns** property.

*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with your:*

*  **Webpack configuration:**

*  **Generated service worker (not minified):**

**Comment by goldhand** [comment]
I don't see why you would want to ignore the gzip files. Why do you want to ignore them?

**Comment by andyrichardson** [comment]
@goldhand we want to ignore gzip files as they are passed from the server when a request is made for a .js file. 

Passing `[ /\.gz$/ ]` to the staticFileGlobsIgnorePatterns property is not preventing files ending in `.gz` from being added to the service worker.
