### ISSUE TITLE
service workers don't handle fetch for favicons, So how to blacklist certain build files?

### ISSUE THREAD

**Issue by jasan-s** [goldhand/sw-precache-webpack-plugin#12]
I am using favicon webpack plugin to generate favicons at build, and due to bug in chrome the favicons are always fetched from network.  From what i understand of service workers, the icons will be download and cached at first visit, so if there are not be used I would rather not waste network resources even at first visit caching them.

**Comment by goldhand** [comment]
There is no way to exclude bundles without just overriding the __staticFileGlobs__ configuration value.

```javascript

plugins: [
  new SWPrecacheWebpackPlugin(
    {
      cacheId: "my-project-name",
      filename: "my-project-service-worker.js",
      staticFileGlobs: [
        // you will need to define which bundles you want to cache here
      ],
    }
  ),
]

```

[__staticFileGlobs__](https://github.com/GoogleChrome/sw-precache#staticfileglobs-arraystring) passes your array of string patterns in to glob.


That aside, I think browsers will behave slightly differently when it comes to requesting favicons. I don't think you can prevent the request from happening but I could be wrong. If they are fetched every visit, you will not save much (if any) bandwidth on trying to cache the asset by preventing it.

**Comment by jasan-s** [comment]
I don't think browsers fetch all the icons or favicons even if there in a link tags( I have 10+ link tags) but i wasn't sure if I added these to service worker to cache them all, if they all would be downloaded regardless of if browser needs them or not.
