### ISSUE TITLE
Using this module breaks the JSON emitted by webpack --profile

### ISSUE THREAD

**Issue by AoDev** [goldhand/sw-precache-webpack-plugin#122]
* [x] **I'm submitting a bug report**

**webpack version:**
3.8.1

**sw-precache-webpack-plugin version**:
0.11.4

**Please tell us about your environment:**
OSX, Node 8.2.1

**Current behavior:**

_context_:
Webpack allows to create a profile of the app with the [profile option](https://webpack.js.org/configuration/other-options/#profile).
This profile is a json having stats that can be consumed by [tools like webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer).

_the problem_:
This plugin logs the following: `Total precache size is about 1.68 MB for 46 resources.`, which ends up in the bundle stats json, resulting in an invalid json file.

The logged message is actually emitted by [sw-precache, here](https://github.com/GoogleChromeLabs/sw-precache/blob/943f1e827aa03be4200789d453d3c9be4921b6cf/lib/sw-precache.js#L280).

**Expected/desired behavior:**

This message should not end up in the stats.json file.

**How to reproduce**

- You can use the [example of sw-precache-webpack-plugin repo](https://github.com/goldhand/sw-precache-webpack-plugin/tree/master/examples). (this repo).

- Modify the example, _webpack script_ in package.json by adding `--profile --json > webpack.stats.json`. 
It should look like this: `"webpack": "NODE_ENV=production ./node_modules/.bin/webpack --config=webpack.config.js --progress --profile --json > webpack.stats.json"`

- run the script with `npm run webpack`

- check the generated webpack.stats.json file, it will be corrupted, with the first line being: `Total precache size is about 847 kB for 2 resources.`

**Comment by goldhand** [comment]
You can use the [`logger`](https://github.com/GoogleChromeLabs/sw-precache#logger-function) option to fix this:

```js
SWPrecacheWebpack({
  logger: function() {},
});
```

Going to close this, feel free to open if there is still an issue.
