### ISSUE TITLE
What is the license on this project?

### ISSUE THREAD

**Issue by DanPen** [goldhand/sw-precache-webpack-plugin#128]
* [x] **I'm submitting a support request**

Is this project open-sourced? I am needing to create a custom service worker after webpack's compilation phase and I'm interested in borrowing some code from `src/index.js` as it's the behavior I need from webpack.

Thank you.

**Comment by goldhand** [comment]
It is ISC license:

https://github.com/goldhand/sw-precache-webpack-plugin/blob/master/package.json#L37

**Comment by goldhand** [comment]
Added an explicit license in `v0.11.5` https://unpkg.com/sw-precache-webpack-plugin@0.11.5/LICENSE
