### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by moimael** [goldhand/sw-precache-webpack-plugin#135]
* [ ] **I'm submitting a bug report**
* [x] **I'm submitting a feature request**
* [ ] **I'm submitting a support request**

**webpack version:**
4.x

**sw-precache-webpack-plugin version**:
0.11.4

**Please tell us about your environment:**
Linux Fedora 27

**Browser:** Chrome 64

**Expected/desired behavior:**
Now that webpack 4 is in beta and 1 month away from final release, this plugin should probably be upgraded to work with it.

**Comment by lencioni** [comment]
Aside from updating the peerDependencies semver range to allow for v4, what else needs to be done here?

**Comment by andriijas** [comment]
Depends I guess but the changelog says

```
plugin method is backward-compatible
Plugins should use Compiler.hooks.xxx.tap(<plugin name>, fn) now
```

webpack/webpack#6357
