### ISSUE TITLE
Offline support after inital visit

### ISSUE THREAD

**Issue by gerhardsletten** [goldhand/sw-precache-webpack-plugin#136]
* [ ] **I'm submitting a bug report**
* [ ] **I'm submitting a feature request**
* [x] **I'm submitting a support request**

**webpack version:**
3.6.0

**sw-precache-webpack-plugin version**:
0.11.4

**Please tell us about your environment:**
Next.js webapp

**Browser:** [Chrome 63]

**Current behavior:**
Probably a noob-question, but how do people get the inital visit into cache? 

In the webapp I see that I have to do a refresh or returned visit to ig the homepage to have this page also available offline. Guess this is because the service-worker registration is happening after resources for the first page is loaded so they are not cached by sw-precache

**Comment by goldhand** [comment]
This tool will create a service worker that will **precache** all the assets you specify with it. This way, during subsequent page loads, the specified recourses are loaded from the cache.
