### ISSUE TITLE
How to add custom files which not generated by webpack into precache list?

### ISSUE THREAD

**Issue by JounQin** [goldhand/sw-precache-webpack-plugin#137]
* [ ] **I'm submitting a bug report**
* [x] **I'm submitting a feature request**
* [x] **I'm submitting a support request**

**webpack version:**
3.10.0

**sw-precache-webpack-plugin version**:
0.11.4

**Please tell us about your environment:**
macOS 10.13.3

**Browser:**
Chrome 64

**Current behavior:**
No way to add custom file which is not generated by webpack into precache list

**Expected/desired behavior:**
Add an option to add custom files, `webpack vendors dll` for example
https://webpack.js.org/plugins/dll-plugin/

*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with your:*

**Webpack configuration:**
https://github.com/JounQin/Rubick/blob/master/build/vue-client.ts#L66-L84

**Comment by goldhand** [comment]
Does `importScripts` fulfill this behavior?

**Comment by JounQin** [comment]
@goldhand I've tried `importScripts`, but it does not work`.

![image](https://user-images.githubusercontent.com/8336744/35958267-cf6110f2-0cda-11e8-9015-31b5375a93c5.png)

**Comment by MikaelEdebro** [comment]
I am also wondering about this feature. I'm trying to cache a font from Google Web Fonts:
https://fonts.googleapis.com/icon?family=Material+Icons

**Comment by goldhand** [comment]
Oh I see, @MikaelEdebro and @JounQin, you want to add additional files to the be precached. Sorry, `importScripts` is for adding code to your service worker. If you just want to cache things like Google web fonts or any file not emitted by webpack, you want to use a [**runtimeCaching**](https://github.com/GoogleChromeLabs/sw-precache#runtimecaching-arrayobject) strategy. Something like this for webfonts:

```js
   runtimeCaching: [
        {
          handler: 'cacheFirst',
          urlPattern: /^https:\/\/fonts\.googleapis\.com\/icon/,
          options: {
            cache: {
              maxEntries: 10,
              name: 'fonts,
            },
          },
        },
  ],
```
