### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by bensyverson** [goldhand/sw-precache-webpack-plugin#145]
Hi, we're hoping to use this repo on a project, but it has no license, so by default it's a conventional copyright without permission for anyone else to use or reproduce. Would you mind adding an explicit license?

**Comment by goldhand** [comment]
Sure thing, I will add a LICENSE file. It's currently "ISC" according to package.json

**Comment by goldhand** [comment]
Added in `v0.11.5` https://unpkg.com/sw-precache-webpack-plugin@0.11.5/LICENSE
