### ISSUE TITLE
Breaks webpack stats (the --json flag)

### ISSUE THREAD

**Issue by eirslett** [goldhand/sw-precache-webpack-plugin#15]
When running webpack --json we get something like:

```json
{
  "build-stats-etc": "here..."
}
Caching static resource "bla-bla-bla.js" (64.77 kB)
...
Total precache size is about etc MB for xxx resources.
```

which is invalid JSON. The sw-precache log output is appended to the JSON output.
Could this be due to the plugin logging to stdout, while when running webpack with the --json flag, it's supposed to log to stderr? (or suppress logging?)

**Comment by goldhand** [comment]
set the sw-precache logger option to `function() {}` and it will remove that from the output
Might need to remove this output by default...

**Comment by goldhand** [comment]
example

```
const SW_PRECACHE_CONFIG = {
  cacheId: SERVICE_WORKER_CACHEID,
  filename: SERVICE_WORKER_FILENAME,
  staticFileGlobsIgnorePatterns: SERVICE_WORKER_IGONRE_PATTERNS,
  logger: function() {},
};
```
