### ISSUE TITLE
runtimeCaching network first then cache

### ISSUE THREAD

**Issue by MuzammilRafay** [goldhand/sw-precache-webpack-plugin#164]
Hey i want to first check network then cache if network is not available.
any idea about this pattern in cache ???

runtimeCaching: [
            {
                urlPattern: /^https:\/\/fonts\.googleapis\.com\//,
                handler: 'cacheFirst'
            },
            {
                urlPattern: /^https:\/\/www\.thecocktaildb\.com\/images\/media\/drink\/(\w+)\.jpg/,
                handler: 'cacheFirst'
            }
        ],

**Comment by carlesjavierre** [comment]
Did you try with

handler: 'networkFirst'

It happened to work for me.

**Comment by goldhand** [comment]
Closing: unable to reproduce
