### ISSUE TITLE
How to importScripts that are generated by webpack?

### ISSUE THREAD

**Issue by Hosar** [goldhand/sw-precache-webpack-plugin#19]
Hi!, I need some help. How do I import an script that is generated by webpack?
I mean in the import section how do I pass the **hash** that is generated by webpack, so when the service worker file is created, it can import the correct script.
_(this is not an issue, I just need some help. Please tell me If I need to open a question on stackoverflow and what tag should I use. Thanks in advance)_
```
new swPrecacheWebpackPlugin(
      {
        cacheId: 'myCoffeeB',
        filename: 'swPrecache.js',
        staticFileGlobsIgnorePatterns: SERVICE_WORKER_IGONRE_PATTERNS,
        maximumFileSizeToCacheInBytes: 4194304,
        importScripts:['sw-[hash].js'],
   }
```

**Comment by goldhand** [comment]
@Hosar just to clarify, are the scripts you want to import entry points in your webpack config?

e.g:

```javascript
...
  entry: {
    sw: path.resolve(__dirname, 'src/sw-precache-script'),
  },
  output: {
    filename: '[name]-[hash].js',
  },
```

**Comment by Hosar** [comment]
Yes, particularly I want to import the sw entry :
It's possible?
```
entry: {
    app:entryDir,    
    sw:swPath
  },
  output: {
    path: outDir,
    filename: '[name]-[hash].js',
    sourceMapFilename: '[file].map',
    publicPath: 'http://localhost:4200/dist/'
  },  
```

**Comment by goldhand** [comment]
Currently not possible but I can work on a pr over the weekend or you can. Would be very useful feature

**Comment by goldhand** [comment]
Thanks again for this @Hosar

**Comment by sohailalam2** [comment]
Unfortunately, this does not work with https://github.com/vuejs-templates/pwa 's webpack scripts. 

I tried using the following configurations: 

```js
entry: {
    app: './src/main.js',
    'sw': './src/workers/sw.js',
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
.
.
.
plugins: [
// service worker caching
    new SWPrecacheWebpackPlugin({
      cacheId: 'pwa-vue',
      filename: 'service-worker.js',
      staticFileGlobs: ['dist/**/*.{js,html,css}'],
      minify: true,
      stripPrefix: 'dist/',
      importScripts: [
        utils.assetsPath('js/sw.[hash].js')
      ],
    }),
]
```

There are potentially 2 problems here - 

1. The hash  generated by webpack while transpiling the files is different. I believe it has something to do with chunkhash. The hash that importScript [hash] uses is different.

2. The webpack pipeline encapsulates the importScript service-worker code with **webpackJsonp**, which renders it invalid in the service worker context.
