### ISSUE TITLE
compress generated file

### ISSUE THREAD

**Issue by neeharv** [goldhand/sw-precache-webpack-plugin#21]
The generated service worker js file can be upwards of 24KB in size. Having the option to minimize or pass it through uglify would be great.

Unless I'm missing something, and it's possible to send the result of this plugin through to the `UglifyJS` plugin?

**Comment by goldhand** [comment]
That would be useful and wouldn't be difficult to add. Somewhere around here maybe?https://github.com/goldhand/sw-precache-webpack-plugin/blob/master/src/index.js#L103

**Comment by neeharv** [comment]
Yup, that looks easy enough to add in. I'll try and get a PR out in the
next couple of days with this.
