### ISSUE TITLE
Hash is not preserved on importScripts

### ISSUE THREAD

**Issue by Hosar** [goldhand/sw-precache-webpack-plugin#27]
If I set importScripts:['sw-[hash].js'], the [hash] is not preserved so when executing webpack in watch mode it always return the first hash that was set and not the new one.

**Comment by goldhand** [comment]
fixed in https://github.com/goldhand/sw-precache-webpack-plugin/commit/4443652ea2da850366191c28f12dcf3cfbf9bdcd
