### ISSUE TITLE
can't success. Already has Access-Control-Allow-Origin: *

### ISSUE THREAD

**Issue by bodyno** [goldhand/sw-precache-webpack-plugin#30]
The error message is :

Fetch API cannot load https://xzy.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://xxx.net' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by bodyno** [comment]
My mistake

**Comment by yuxizhe** [comment]
how to solve it? I have the same problem. Thanks

**Comment by bodyno** [comment]
Can't do anything to this.
Service worker doesn't allow.

**Comment by yuxizhe** [comment]
Can I use `fetch('.......js', {mode: 'no-cors'})`  ?
or set CDN header 'Access-Control-Allow-Origin'?

**Comment by bodyno** [comment]
Sorry. The SPEC doesn't allow.
