### ISSUE TITLE
Misspelled constant in examples/webpack.config.js

### ISSUE THREAD

**Issue by capouch** [goldhand/sw-precache-webpack-plugin#31]
It's wrong the same way in both places, so it doesn't have any effect on operations, but this is the kind of thing that might bite somebody later.

IGONRE -> IGNORE

`const SERVICE_WORKER_IGONRE_PATTERNS = [/dist\/.*\.html/];
const SW_PRECACHE_CONFIG = {
  cacheId: SERVICE_WORKER_CACHEID,
  filename: SERVICE_WORKER_FILENAME,
  staticFileGlobsIgnorePatterns: SERVICE_WORKER_IGONRE_PATTERNS,`

**Comment by goldhand** [comment]
haha good catch, want to send a pr for that?
