### ISSUE TITLE
cache.add() returning Error: DOMException Quota exceeded.

### ISSUE THREAD

**Issue by bshenk** [goldhand/sw-precache-webpack-plugin#33]
In line 137 of the generated service.worker.js file, the return values from the cache.add calls are returning the error listed in the title: DOMException Quota Exceeded. I did a good amount of research on the error earlier today, but the only thing I could find was that it was somehow linked to localStorage. Any ideas?

**Comment by bshenk** [comment]
Just tried re-building my app on macOS Sierra 10.12.1 (instead of Windows 10) and the error is not thrown and the service worker is successfully registered/installed. Using Chrome Canary (57.0.2959.0) on both. Any idea why this would fail on a build made while on Windows?

**Comment by goldhand** [comment]
Thats weird it only happens in windows... Possibly a [sw-precache](https://github.com/GoogleChrome/sw-precache) issue?

**Comment by goldhand** [comment]
Closing, maybe this was related to windows issues but I haven't seen anything like this for a while.

**Comment by mrasoahaingo** [comment]
Hi, I get the same error on last version of chrome, deployed on now here https://pwa-ykcahrrcnz.now.sh/ :(

**Comment by goldhand** [comment]
Sounds like you're saving too much to the cache. There's a limit to the amount of storage each website is given (depending on the browser). I just noticed Chrome added a diagram in the "Application" tab of dev tools that show the storage used / storage quota.

**Comment by jeffposnick** [comment]
In addition to being able to check via the Application tab, there's a programmatic way to check your current and maximum storage usage: https://developers.google.com/web/updates/2017/08/estimating-available-storage-space
