### ISSUE TITLE
webpack 2.2.0-rc.2 compatibility

### ISSUE THREAD

**Issue by sdumetz** [goldhand/sw-precache-webpack-plugin#37]
I've upgraded to webpack 2.2.0-rc.2 and there seems to be no trouble for me at least.

I don't know if you have some sort of validation process to check for full compatibility, and in this case, if you'd like some help to get it done? Otherwise, juste update peerDependencies to accept webpack@^2.2.0-beta ?

**Comment by goldhand** [comment]
Sure what were you thinking for validating 2.2.0-beta works?
The unit tests should help validating.
I use the example project for integration testing. Maybe update the webpack dependency there too?
What other ideas do you have?

**Comment by sdumetz** [comment]
Unless you have more complex use cases you want to test, considering webpack@2.x.x is still beta, i'd suggest to just upgrade and see if anyone complain. It's not like someone could install it by mistake as they have to explicitly require install a specific version.

**Comment by stevewillard** [comment]
For what it's worth, I'm using `2.2.0-rc.3` and this plugin works great.

**Comment by goldhand** [comment]
Ok I set peer dependencies to: `^1 || ^2.1.0-beta || ^2.2.0-beta`
