### ISSUE TITLE
Fetch event listener not working

### ISSUE THREAD

**Issue by nitish24p** [goldhand/sw-precache-webpack-plugin#39]
i have the following webpack config
```javascript
new SWPrecacheWebpackPlugin({
        //cacheId: '[app_name]',
        filename: 'connect-service-worker.js',
        staticFileGlobs: ['./views/build/*'],
        dontCacheBustUrlsMatching: [/./]
      }),
```
```pug
html  
  head
    title= title
    meta(name='viewport', content='width=device-width, initial-scale=1.0') 
  body
    #app
    script(src="build/" + vendor)
    script(src="build/" + bundle)
    script.
      if(navigator.serviceWorker) {
        navigator.serviceWorker.register('./build/connect-service-worker.js')
          .then(function(registration) {
            console.log('Service worker successfully installed with scope',registration.scope)
          })
          .catch(function(err) {
            // registration failed :(
            console.log('ServiceWorker registration failed: ', err);
          });
      } 

```
i am caching the entire build folder. My service worker is also created in the build folder itself. The above code installs the service worker correctly, and i can see my assets cached, but the next time i refresh the browser a fresh request is made, even on putting a breakpoint in the fetch listener, i dont see the flow going into that block. Anything i'm doing wrong. Any helo would be great.

**Comment by phun-ky** [comment]
I'm experiencing the same thing. I see no effect of this plugin.

With this config

    new SWPrecacheWebpackPlugin({
      cacheId: 'my-project',
      filename: 'my-project-sw.js'
    })

The service worker is activated and running, but nothin in the network tab indicates that the service worker is working :( I can see that the generated service worker file contains references to the files that's precached.

**Comment by nitish24p** [comment]
Ok so  after doing some research i got a work around. The service worker has to be at the same level as your index.html. The following config worked for me.

```javascript
new SWPrecacheWebpackPlugin({
        cacheId: 'connect',
       filename: 'connect-service-worker.js',
        filepath: './views/connect-service-worker.js',
       staticFileGlobs: ['./views/build/*'],
      }),
```

**Comment by goldhand** [comment]
yeah @nitish24p , this seems to be a common problem. I think adding a warning message if you have a service worker in a directory that is deeper than `webpack.output.path`.
```
compilation.warnings.push(new Error(`Service Worker Filepath: ${filepath} does not share the same origin as your ${webpack.output.path}. This may prevent the service worker from working correctly.`));
```

**Comment by phun-ky** [comment]
I did the same thing as @nitish24p , but results are still the same, nothing is cached with the service worker

**Comment by goldhand** [comment]
Added a warning https://github.com/goldhand/sw-precache-webpack-plugin/commit/a38ce9a055726498dca4fc53877f33a95285b65d
