### ISSUE TITLE
Non root-relative URLs

### ISSUE THREAD

**Issue by jschr** [goldhand/sw-precache-webpack-plugin#4]
My app is currently hosted in a subfolder of the domain and spent some time debugging why all the urls being fetched by sw-precache were root-relative (ie. `/app.js`) instead of relative (ie. `app.js`). I don't believe there is an issue but I'm posting this in case it helps anyone else. Feel free to close.

The root of the issue is that sw-precache-webpack-plugin will use the webpack output path as the `stripPrefix` param to sw-precache. My webpack config looked something like this

```
{
  output: {
    filename: 'app.js',
    path: path.resolve(__dirname, 'dist', env)
  },
  plugins: [
    new SWPrecacheWebpackPlugin({
      cacheId: require('./package.json').name
    })
  ]
}
```

The fix is to set stripPrefix to replace the output path and the leading '/' manually

```
{
  output: {
    filename: 'app.js',
    path: path.resolve(__dirname, 'dist', env)
  },
  plugins: [
    new SWPrecacheWebpackPlugin({
      cacheId: require('./package.json').name,
      stripPrefix: path.resolve(__dirname, 'dist', env) + '/',
      replacePrefix: ''
    })
  ]
}
```

**Comment by goldhand** [comment]
@jschr good find, I think it would be better to default to relative paths.

**Comment by jschr** [comment]
agreed that it might be a better default but would you still be able to allow for root-relative urls (with a proceeding `/`)?

The source of most of my confusion was just not being aware that output.path was being used automatically as the stripPrefix although it did make sense once I realized. The first thing I tried was

```
new SWPrecacheWebpackPlugin({
  cacheId: require('./package.json').name,
  stripPrefix: '/'
})
```

Which results in full file path urls without the proceeding `/` ie. `Users/myuser/myapp/dist/development/app.js`. Once I realized output.path was being used as the default stripPrefix I was able to figure out a solution.

Perhaps another solution is to append whatever stripPrefix is provided with the plugin config to the default output.path instead of overriding.

**Comment by goldhand** [comment]
@jschr if we remove the `/` prefix by default you can can allow for root-relative urls again by specifying the `replacePrefix: '/'` parameter:

```javascript
    new SWPrecacheWebpackPlugin({
      cacheId: require('./package.json').name,
      replacePrefix: '/',
    }),
```

I will update docs about the output.path usage so its clearer.

A good idea but I don't want to prevent user's from skipping the plugins functions and passing their own options into sw-precache.

**Comment by goldhand** [comment]
Updated in `0.3.0` :smile:
