### ISSUE TITLE
Set up SWPrecache to cache index and return 200 when offline

### ISSUE THREAD

**Issue by phun-ky** [goldhand/sw-precache-webpack-plugin#42]
I am trying to make the webapp usable offline, how do I do this with this plugin? 

I have this config:

    new SWPrecacheWebpackPlugin(
      {
        cacheId: 'my-project',
        filename: 'my-project-sw.js',
        filepath: publicDir + '/my-project-sw.js',
        staticFileGlobs: [
          assetsDir + '/**/*.{json,webmanifest}',
          assetsDir + '/**/*.css',
          assetsDir + '/**/*.{ttf,woff,woff2,eof}',
          assetsDir + '/**/*.js',
          assetsDir + '/**/*.map',
          publicDir + '/index.html',
          assetsDir + '/**/*.{png,jpg,jpeg,ico,gif,svg}'
        ],
        verbose: true,
        navigateFallback: '/index.html',
        runtimeCaching: [{
          urlPattern: /\/api\//,
          handler: 'networkFirst'
        },{
          urlPattern: /\/assets\//,
          handler: 'cacheFirst'
        }]
      }
    )

**Comment by goldhand** [comment]
Any chance the discussion at #18 helps you?
If you're trying to do something with the Lighthouse Chrome plugin then its very likely to have your answer, if not, there's a lot of useful info there.

**Comment by phun-ky** [comment]
Hm, I've just glanced at it, but it doesn't look like much. Will check it out later. I think I am a bit closer with this config:

    new SWPrecacheWebpackPlugin(
      {
        cacheId: 'my-project',
        filename: 'my-project-sw.js',
        filepath: publicDir + '/my-project-sw.js',
        staticFileGlobs: [
          'dist/assets/*.{json,webmanifest}',
          'dist/assets/*.css',
          'dist/assets/*.{ttf,woff,woff2,eof}',
          'dist/assets/*.js',
          'dist/assets/*.map',
          'public/index.html',
          'dist/assets/*.{png,jpg,jpeg,ico,gif,svg}'
        ],
        verbose: true,
        navigateFallback: '/index.html',
        runtimeCaching: [{
          urlPattern: /\/api\//,
          handler: 'networkFirst'
        },{
          urlPattern: /\/assets\//,
          handler: 'cacheFirst'
        }]
      }
    )

The static files are only picked up if I do `'dist/assets/...` resulting in `http://localhost:8080/dist/assets/favicon-128.png` when it should be: `http://localhost:8080/assets/favicon-128.png`

Same with `public/index.html`, this should be `http://localhost:8080/index.html`, but it is `http://localhost:8080/public/index.html`

The assets are in my project like this:  `/dist/assets/*.*` which is generated and `/public/*.*`, but they are served in express like `/assets/` and `/`. Is there a way to circumvent the behaviour described over?

**Comment by phun-ky** [comment]
I think I can use `replacePrefix`: https://github.com/GoogleChrome/sw-precache#replaceprefix-string somehow, but what do I input? The string to be replaced? The string to replace with? What is replaced?

**Comment by phun-ky** [comment]
Yet another rubberduckie session.. 

    new SWPrecacheWebpackPlugin(
      {
        cacheId: 'my-project',
        filename: 'my-project-sw.js',
        filepath: publicDir + '/my-project-sw.js',
        staticFileGlobs: [
          'dist/assets/*.{json,webmanifest}',
          'dist/assets/*.css',
          'dist/assets/*.{ttf,woff,woff2,eof}',
          'dist/assets/*.js',
          'dist/assets/*.map',
          'public/index.html',
          'dist/assets/*.{png,jpg,jpeg,ico,gif,svg}'
        ],
        stripPrefixMulti: {
          'dist/assets/': 'assets/',
          'public/': ''
        },
        verbose: true,
        navigateFallback: '/index.html',
        runtimeCaching: [{
          urlPattern: /\/api\//,
          handler: 'networkFirst'
        },{
          urlPattern: /\/intercom\//,
          handler: 'networkFirst'
        }]
      }
    )

Closing this

**Comment by goldhand** [comment]
Haha good stuff, is your `index.html` emitted by webpack? Meaning is it generated with some javascript html template loader? If it's one of your assets, you can just omit the `staticFileGlobs` and  `replacePrefix`. This plugin will add all your emited assets to the `staticFileGlobs`, use your webpack output path for the `stripPrefix` and use your webpack public path for the `replacePrefix`

**Comment by phun-ky** [comment]
My `index.html` is a static file, for now. 

I realized that `staticFileGlobs` is populated with the assets if not set, but the `sw-precache` documentation says `staticFileGlobs` has to be set. Maybe a clarification in the docs?

**Comment by goldhand** [comment]
Sorry if you missed it or if its not clear but its documented a couple times here: https://github.com/goldhand/sw-precache-webpack-plugin#configuration
And in the examples here: https://github.com/goldhand/sw-precache-webpack-plugin/blob/master/examples/webpack.config.js#L11
