### ISSUE TITLE
Upgrade sw-precache dependency

### ISSUE THREAD

**Issue by mikestead** [goldhand/sw-precache-webpack-plugin#43]
Would we be able to update to the latest [sw-precache version](https://github.com/GoogleChrome/sw-precache/releases)? Currently it looks like this lib depends on `v4.1.0` released last sept, but it's now up to `v4.3.0`, with the latest release including some useful bug fixes.

**Comment by goldhand** [comment]
I can update this, thanks!

**Comment by unindented** [comment]
This seems fixed. Should it be closed?

**Comment by mikestead** [comment]
Yep seems up to date in latest release 👍
