### ISSUE TITLE
Items are added to Cache Storage but don't have response OK ?

### ISSUE THREAD

**Issue by stevenfitzpatrick** [goldhand/sw-precache-webpack-plugin#45]
Just noticed that items added via this plugin get added to Cache Storage correctly, but seem to have an empty response instead of the response (OK).

![captureswcache](https://cloud.githubusercontent.com/assets/23268855/22404033/e48068f8-e61f-11e6-8995-d750608a4e03.PNG)

```
new SWPrecacheWebpackPlugin({
    cacheId: pkg.name,
    filename: 'sw.js',
    minify: true,
    maximumFileSizeToCacheInBytes: 4194304,
}),
```

Everything seems to be working and a page hit it responds with 200 from Service Worker, but on other sites with Service Workers I see 200 (OK) from Service Worker.

**Comment by goldhand** [comment]
Thanks for noticing this @stevenfitzpatrick but this is something that would have to be implemented in [sw-precache](https://github.com/GoogleChrome/sw-precache).

**Comment by jeffposnick** [comment]
See http://stackoverflow.com/questions/41920849/application-cache-storage-items-have-empty-response/41983172#41983172
