### ISSUE TITLE
Consider linking to the recommended sw registration script

### ISSUE THREAD

**Issue by jschr** [goldhand/sw-precache-webpack-plugin#5]
For newcomers such as myself it would be useful to provide a link to the recommended service worker install script: https://github.com/GoogleChrome/sw-precache/blob/master/demo/app/js/service-worker-registration.js

This is mentioned in the docs for `sw-precache` but might be useful here in case people land on this plugin first when searching for a webpack plugin for service workers.

**Comment by goldhand** [comment]
Linked! Thanks 😄
