### ISSUE TITLE
'/' not caching 

### ISSUE THREAD

**Issue by rumanbsl** [goldhand/sw-precache-webpack-plugin#50]
Is it normal behaviour:

![image](https://cloud.githubusercontent.com/assets/13895272/23029819/69c99360-f474-11e6-9107-7eeb22a1c87d.png)

I want to have the "http://localhost:8000/" cached, so that the offline-functionality works. 

Below is my sw-precache setup 
![image](https://cloud.githubusercontent.com/assets/13895272/23030008/1136c10e-f475-11e6-8a2a-a3487c2ced65.png)

**Comment by rumanbsl** [comment]
My bad, rimraf-ing public directory took away html file. Fixed.

**Comment by xerosanyam** [comment]
so what was the urlPattern that you added ?
