### ISSUE TITLE
options.noWarning to suppress the warning

### ISSUE THREAD

**Issue by didi0613** [goldhand/sw-precache-webpack-plugin#52]
Hi all,
Does anyone knows if adding `options.noWarning` to suppress the warning https://github.com/goldhand/sw-precache-webpack-plugin/blob/master/src/index.js#L102 is ok?

**Comment by goldhand** [comment]
Doesn't webpack have a log level setting?

**Comment by didi0613** [comment]
@goldhand Hi Will,
Thanks for your reply. We don't necessary want to turn off all other warnings. Since we may actually want to use a custom path and aware of it.

**Comment by goldhand** [comment]
@didi0613 if you sent a pr with `options.debug` I would accept it.

Set default to `false` or 0 and check that it is true in https://github.com/goldhand/sw-precache-webpack-plugin/blob/master/src/index.js#L102

**Comment by goldhand** [comment]
Will be released in `0.9.2`
