### ISSUE TITLE
Lower engines requirement to support node 4?

### ISSUE THREAD

**Issue by jeffposnick** [goldhand/sw-precache-webpack-plugin#54]
The underlying `sw-precache` library has an [`engines` requirement](https://github.com/GoogleChrome/sw-precache/blob/26bbf507379f8c740b0e18b91843f00bfcfc2506/package.json#L21) of node 4+. I noticed that your library requires node 5+ (see https://github.com/facebookincubator/create-react-app/pull/1728#issuecomment-284790918).

Are you using anything specific to node 5 that won't work in node 4? If no, could you lower the `engines` requirement to support node 4 as well?

**Comment by wtgtybhertgeghgtwtg** [comment]
`index.js` [makes use of the spread operator](https://github.com/goldhand/sw-precache-webpack-plugin/blob/master/src/index.js#L67-L68), which [isn't available until `node@5`](http://node.green/#ES2015-syntax-spread-------operator).

**Comment by goldhand** [comment]
I don't think there is. I will change that asap. Sorry for being MIA on the other review requests @jeffposnick. I've been swamped at my day job

**Comment by goldhand** [comment]
Updated this in [0.9.1](https://github.com/goldhand/sw-precache-webpack-plugin/tree/v0.9.1) Should be ready for https://github.com/facebookincubator/create-react-app/issues/1728

**Comment by jeffposnick** [comment]
You're a hero for maintaining this repo, @goldhand!

**Comment by goldhand** [comment]
Aw, thanks! Its not much work and I enjoy doing it :smile:
