### ISSUE TITLE
Uncaught (in promise) TypeError: Add/AddAll does not support schemes other than "http" or "https"

### ISSUE THREAD

**Issue by fengxinming** [goldhand/sw-precache-webpack-plugin#57]
service-worker.js:137 Uncaught (in promise) TypeError: Add/AddAll does not support schemes other than "http" or "https"

You can pull my project to debug the problem:

git clone https://github.com/fengxinming/koa2-vue-hackernews
cd koa2-vue-hackernews
npm install
npm run build
npm start

Input "http://localhost:5500" on your Chrome

**Comment by anshchauhan** [comment]
@fengxinming Getting the same error. Found any fix?

**Comment by fengxinming** [comment]
@anshchauhan Nothing to be found, I haven't used it

**Comment by goldhand** [comment]
Sounds like you're importing scripts from a different protocol that `http` or `https`. Assuming this is a browser limitation.
