### ISSUE TITLE
cached but not loaded through service worker cache

### ISSUE THREAD

**Issue by simran66** [goldhand/sw-precache-webpack-plugin#59]
First of all, awesome plugin. Looks like so much flexibility, the right way!

I have been trying to get my server side rendered react app to be supported offline.I am using this boilerplate

https://github.com/erikras/react-redux-universal-hot-example

My service worker is registered, running and I can see the cached resources in Cache Storage. Basically all of my assets created through webpack are cached. Cool.

Here's a snapshot of that:

![res](https://cloud.githubusercontent.com/assets/4191009/24295757/4c5dce6c-10c2-11e7-9f93-3f5f6b795418.png)

Two problems I am facing:

1. None of the resources, not even the cached ones I see in Cache Storage are getting loaded from service worker but either disk cache or memory cache as I see in my network tab in chrom console

Literally none of them. Attached snapshot:

![res2](https://cloud.githubusercontent.com/assets/4191009/24295837/9186fd4c-10c2-11e7-8764-c3e0cc36c130.png)

2. My website is not working offline even though resources are cached.

![nooffline](https://cloud.githubusercontent.com/assets/4191009/24295860/aaf48b78-10c2-11e7-8fcb-b8c2b258ed0b.png)

Why is that? What do I exactly need to do to make it work offline?

Note: The HTML generated at the server is through a react component that looks like this:

(coming straight from the boilerplate so you could use this boilerplate to reproduce the issue)

(I am using production version here on my local system)

This component gets server side rendered through renderToString function of react.
```

import React, {Component, PropTypes} from 'react';
import ReactDOM from 'react-dom/server';
import serialize from 'serialize-javascript';
import Helmet from 'react-helmet';

/**
 * Wrapper component containing HTML metadata and boilerplate tags.
 * Used in server-side code only to wrap the string output of the
 * rendered route component.
 *
 * The only thing this component doesn't (and can't) include is the
 * HTML doctype declaration, which is added to the rendered output
 * by the server.js file.
 */
export default class Html extends Component {
  static propTypes = {
    assets: PropTypes.object,
    component: PropTypes.node,
    store: PropTypes.object
  };

  render() {
    const {assets, component, store} = this.props;
    const content = component ? ReactDOM.renderToString(component) : '';
    const head = Helmet.rewind();

    return (
      <html lang="en-us">
        <head>
          {head.base.toComponent()}
          {head.title.toComponent()}
          {head.meta.toComponent()}
          {head.link.toComponent()}
          {head.script.toComponent()}

          <link rel="shortcut icon" href="/favicon.ico" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {/* styles (will be present only in production with webpack extract text plugin) */}
          {Object.keys(assets.styles).map((style, key) =>
            <link href={assets.styles[style]} key={key} media="screen, projection"
                  rel="stylesheet" type="text/css" charSet="UTF-8"/>
          )}

          {/* (will be present only in development mode) */}
          {/* outputs a <style/> tag with all bootstrap styles + App.scss + it could be CurrentPage.scss. */}
          {/* can smoothen the initial style flash (flicker) on page load in development mode. */}
          {/* ideally one could also include here the style for the current page (Home.scss, About.scss, etc) */}
          { Object.keys(assets.styles).length === 0 ? <style dangerouslySetInnerHTML={{__html: require('../theme/bootstrap.config.js') + require('../containers/App/App.scss')._style}}/> : null }
        </head>
        <body>
          <div id="content" dangerouslySetInnerHTML={{__html: content}}/>
          <script dangerouslySetInnerHTML={{__html: `window.__data=${serialize(store.getState())};`}} charSet="UTF-8"/>
          <script src={assets.javascript.main} charSet="UTF-8"/>
        </body>
      </html>
    );
  }
}


```

Could I please get some help on this?

**Comment by goldhand** [comment]
Could I see what your configuration for this plugin looks like?

**Comment by simran66** [comment]
@goldhand : Here's what it looks like:

```
    new SWPrecacheWebpackPlugin({
      cacheId: 'react-app2',
      filename: 'serviceworker.js',
      minify: true,
      directoryIndex: '/',
      mergeStaticsConfig: true,
      staticFileGlobsIgnorePatterns: [
        /\.map$/,
        /\.map\.gz$/,
        /sw2.js/
      ],
      runtimeCaching: [
        {
          handler: 'fastest',
          urlPattern: /\/*/,
        }
      ],
      verbose: true
    })
```

**Comment by goldhand** [comment]
@simran66 is this working now? I saw you mention it was working in another thread?

**Comment by simran66** [comment]
Yes please it is. :) I needed to created service worker in static folde and
not in dist insider static folder. Does that make sense?

**Comment by goldhand** [comment]
Yes it does 👍
