### ISSUE TITLE
[Bug] Option 'filename' doesn't name sw correctly

### ISSUE THREAD

**Issue by Luchillo** [goldhand/sw-precache-webpack-plugin#6]
Here's the config:
```js
new SWPrecacheWebpackPlugin({
      cacheId: 'example-cache',
      filename: 'example-sw-precache.js',
      maximumFileSizeToCacheInBytes: 4194304
}),
```

However after build i see that it is being compiled to `service-worker.js` in my output dir.

**Comment by goldhand** [comment]
Oops... its set to ` this.options.filepath` currently.

**Comment by Luchillo** [comment]
Yep, figured out that much, though the code to make that plugin was easier than i tough, i always looked to webpack plugin like a criptic black box.

**Comment by goldhand** [comment]
Ok its fixed now, either use filepath or filename.
