### ISSUE TITLE
Please support [chunkhash] for importScripts

### ISSUE THREAD

**Issue by hulkish** [goldhand/sw-precache-webpack-plugin#60]
Currently only `[hash]` supported for `importScripts`. This means, that if you're trying to reference a file that was generated via `[chunkhash]` - there is no way to use it with `importScripts`

**Comment by goldhand** [comment]
Ok, will be easy to add. Can accept a pr if you get to it first

**Comment by hulkish** [comment]
It will probably be towards the end of this week.. But, i will try to get a pr going for this.

**Comment by hulkish** [comment]
@goldhand So, I'm thinking of tackling this in one of these 2 directions:

### current usage:
**Note:** This usage would still be carefully legacy supported per my approach for implementing this `[chunkhash]` feature. This will be done by converting this strategy to my new format. 

```js
importScripts: [
  'sw.[hash].js'// dynamic string to a literal request path
]
```

### my concept:

```js
importScripts: [
  {
    /**
     * path to original entry point
     * - this path will be not utilized if undefined
     * - this path will be not utilized if undefined
     * @sourcePath {String}
      */
    namedEntry: ''

    /**
     * path to original entry point
     * - this path will be not utilized if undefined
     * - this path will be not utilized if undefined
     * @sourcePath {String}
      */
    publichReferencePath: ''// 
  }
]
```

#### example usage:;
```js
entry : {
  sw: path.resolve(__dirname, 'src/client/sw.js')
},
output: {
  filename: '[name].[chunkhash].js',
  publicPath: '/assets/':
}
[...]
importScripts: [
  {
    namedEntry: 'sw',
    publicReferencePath: '/assets/sw.[chunkhash].js'
  }
]
[...]
```

**Comment by kanzelm3** [comment]
I like it

**Comment by goldhand** [comment]
Looks good to me 😄 

Some thoughts:

What do you think about using the names:
```javascript
importScripts: [
  {
    chunkName: 'sw',
    filename: '/assets/sw.[chunkhash].js'
  }
]
```

Also, we currently use the [`publicPath` from the webpack config and add it to the importScripts](https://github.com/goldhand/sw-precache-webpack-plugin/blob/955514bfdde092e11f1e90920c5c99439c8c2e1c/src/index.js#L132-L136) values. What do you think of that behavior? If we kept that consistent, you would not use the `/assets/` in the `publicReferencePath`:

 ```javascript
output: {
  filename: '[name].[chunkhash].js',
  publicPath: '/assets/':
}
importScripts: [
  {
    chunkName: 'sw',
    filename: 'sw.[chunkhash].js'
  }
]
```
would point to: `/assets/sw.ecd2b16a48d8b92daf31.js`


Alternatively, could we get any of these values from the webpack config?
Maybe use `chunkFilename: "[chunkhash].js"` or something?

**Comment by hulkish** [comment]
@goldhand I agree with your changes, I'll post an update when I have one!

**Comment by goldhand** [comment]
Do you think this related to #7 @hulkish ?

**Comment by hulkish** [comment]
@goldhand yep

**Comment by goldhand** [comment]
@hulkish any progress? If not, I'm going to merge in #63 and you can start from there. It's a pretty big pr

**Comment by hulkish** [comment]
@goldhand i finally have time to do this today... sorry for late update. Does the pr u merged cover this feature? or are we still in need?

**Comment by goldhand** [comment]
Add in #70
