### ISSUE TITLE
Want to skip urls patterns to server only

### ISSUE THREAD

**Issue by KK20994** [goldhand/sw-precache-webpack-plugin#61]
My config is as bellow:
`SWPrecache({
				filename: 'service-worker.js',
				cacheId: 'v5',
				staticFileGlobsIgnorePatterns: [/\.map$/],
				dontCacheBustUrlsMatching: /./,
				navigateFallback: 'index.html',
				runtimeCaching: [{
					handler: 'networkOnly',
					urlPattern: /\/app\//,
				}],
			})`
I have setup of preact, preact-router with default route and webpack.

My requirement is got all urls which has '/app/' in the path go to server but it fallback to index.html and router shows the default rout.

I tried by adding runtimeCaching as well but still result is same.

If I manually modify the get function and check for url path and redirect the code to network it works fine.

Ex: 

`self.addEventListener('fetch', function(event) {
  if (event.request.method === 'GET') {
    // Should we call event.respondWith() inside this fetch event handler?
    // This needs to be determined synchronously, which will give other fetch
    // handlers a chance to handle the request if need be.
    var shouldRespond;

    // First, remove all the ignored parameter and see if we have that URL
    // in our cache. If so, great! shouldRespond will be true.
    var url = stripIgnoredUrlParameters(event.request.url, ignoreUrlParametersMatching);
    shouldRespond = urlsToCacheKeys.has(url);

    if(/\/app\//.test(url))
      return fetch(event.request);`

Let me know is there any other way to do it in config.

**Comment by jeffposnick** [comment]
Setting `navigateFallback: 'index.html'` will, by default, cause all navigations for URLs (that aren't explicitly managed in `sw-precache`'s cache) to be fulfilled with the contents of `index.html`.

If that's not the behavior you want at all, then you don't have to set `navigateFallback`. If you want that behavior, but only for navigations to a subset of URLs, you can make use of the [`navigateFallbackWhitelist` option](https://github.com/GoogleChrome/sw-precache#navigatefallbackwhitelist-arrayregexp), and provide a regular expression that matches the URLs that you want to use `index.html` for. Not that this is a whitelist, not a blacklist, so if you want to mimic a blacklist, using a regex with a [negative assertion](http://stackoverflow.com/questions/1538512/how-can-i-invert-a-regular-expression-in-javascript) is your best bet.

**Comment by KK20994** [comment]
Thanks I will try it out

**Comment by jaspersorrio** [comment]
Hi @KK20994 I am struggling with a problem similar to yours.

I'm curious to note, how did you solve this? Were you able to use sw-precache-webpack-plugin?
Because I don't see an `navigateFallbackWhitelist` option in this plugin.
