### ISSUE TITLE
error in plugin or enviorment

### ISSUE THREAD

**Issue by pulkitnandan** [goldhand/sw-precache-webpack-plugin#64]
Hi,

I'm getting following error while trying to integrate swpreacache plugin.

ERROR in ./~/sw-precache-webpack-plugin/lib/index.js
Module not found: Error: Can't resolve 'fs' in '/home/rohitn/dbs/node_modules/sw-precache-webpack-plugin/lib'
 @ ./~/sw-precache-webpack-plugin/lib/index.js 27:10-23
 @ ./nuxt.config.js
 @ ./plugins/axios.js
 @ ./~/babel-loader/lib?{"presets":["vue-app"],"cacheDirectory":false}!./~/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js

Any idea what such error mean?

**Comment by goldhand** [comment]
why are parts crossed out?

Looks like an issue with `fs` not being resolved. It's a core nodejs module so I'm not sure why it's not being resolved.

**Comment by goldhand** [comment]
If thats's the issue, it might be resolved when #63 is merged. It removes the `fs` dependency

**Comment by goldhand** [comment]
try:
```
"browser": { "fs": false }
```
or see: https://github.com/pugjs/pug-loader/issues/8#issuecomment-55568520
