### ISSUE TITLE
How to use with multiple service workers

### ISSUE THREAD

**Issue by BorntraegerMarc** [goldhand/sw-precache-webpack-plugin#67]
## **BEFORE YOU SUBMIT** please read the following:

* [ ] **I'm submitting a bug report**
* [ ] **I'm submitting a feature request**
* [X] **I'm submitting a support request**

**webpack version:**
2.2.1

**sw-precache-webpack-plugin version**:
0.9.1

I have an additional service worker at the moment, that handles push notifications. How can I combine the generated one which handles the fetches and my current one?

**Comment by BorntraegerMarc** [comment]
Friendly ping to @goldhand :)

**Comment by goldhand** [comment]
How about using [importScripts](https://github.com/GoogleChrome/sw-precache#importscripts-arraystring)?

**Comment by BorntraegerMarc** [comment]
Jep just saw it. Closing...
