### ISSUE TITLE
chunk files are not caching

### ISSUE THREAD

**Issue by pavankumarkatakam** [goldhand/sw-precache-webpack-plugin#7]
all static files are cached but no the chunk files like `1.js`,`2.js` and entry points also.

**Comment by goldhand** [comment]
Thanks @pavankumarkatakam good catch

**Comment by tleunen** [comment]
Hey @goldhand, do you have any update on this issue?

**Comment by goldhand** [comment]
I haven't started working on this yet

**Comment by hulkish** [comment]
@goldhand I feel like this can be solved by: https://github.com/goldhand/sw-precache-webpack-plugin/pull/70

**Comment by goldhand** [comment]
Added in #70
