### ISSUE TITLE
Npm has version 0.10.1 but code is not in master

### ISSUE THREAD

**Issue by moimael** [goldhand/sw-precache-webpack-plugin#71]
Hi,

I noticed that version 0.10.1 is available on npm since a few days, but the code is not available on github, nor the release, and there is no changelog. It looks a bit suspicious, any reason for that ? 

Thanks !

**Comment by goldhand** [comment]
Oops! https://github.com/goldhand/sw-precache-webpack-plugin/commit/798b82375f818b7a516efcc1c0141921b54be624

@moimael I noticed some things were making it into the build so I updated the npm ignore file. Should the change log be included in builds?
