### ISSUE TITLE
Callback after precache is complete

### ISSUE THREAD

**Issue by scriptPilot** [goldhand/sw-precache-webpack-plugin#73]
* [ ] **I'm submitting a bug report**
* [ ] **I'm submitting a feature request**
* [x] **I'm submitting a support request**

Hi there! First of all, thank you for the great piece of code. I wanted to know if there is a callback after everything is precached?

**Comment by hulkish** [comment]
@scriptpilot `sw-precache-webpack-plugin` uses the `after-emit` compilation event. So, in theory you could just listen for 'done' (which occurs next in line after all `after-emit` handlers are complete. 

Or, you could also listen for `after-emit` qnd simply include your plugin **after** `sw-precache-webpack-plugin` in your webpack config. 

If we were to create a new event specifically for this.. I'm afraid it would just be redundant. Hope that helps.

**Comment by goldhand** [comment]
Both of @hulkish suggestions will work. Closing

**Comment by scriptPilot** [comment]
@hulkish, @goldhand - Thanks!
