### ISSUE TITLE
staticFileGlobs not working as expected

### ISSUE THREAD

**Issue by agnivade** [goldhand/sw-precache-webpack-plugin#75]
## **BEFORE YOU SUBMIT** please read the following:

[x] **I'm submitting a bug report**
[ ] **I'm submitting a feature request**
[ ] **I'm submitting a support request**

**webpack version:**
2.3.3

**sw-precache-webpack-plugin version**:
0.11.0

**Please tell us about your environment:**
Linux 

**Browser:** [ Chrome 56]

I am using staticFileGlobs along with mergeStaticsConfig=true.

**Current behavior:**
The files in staticFileGlobs do not appear in the service-worker.js Only webpack emitted assets are added.

**Expected/desired behavior:**
Both staticFileGlobs and webpack emitted assets should come in the service-worker.js

*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with your:*

*  **Webpack configuration:**
https://github.com/agnivade/adda/blob/master/build/webpack.prod.conf.js#L91

*  **Generated service worker (not minified):**
The only part which differs is the preCacheConfig variable.
```
var precacheConfig = [["/index.html","372c2e57e5778571959a83e348cc3944"],["/manifest.json","59a31cd89994c87b623b56362d9de028"],["/static/css/app.182ef116fc39799bbd63ba0b4f84725e.css","215f3c68067cea5033c4f7806380ecb8"],["/static/fonts/fontawesome-webfont.674f50d.eot","674f50d287a8c48dc19ba404d20fe713"],["/static/fonts/fontawesome-webfont.af7ae50.woff2","af7ae505a9eed503f8b8e6982036873e"],["/static/fonts/fontawesome-webfont.b06871f.ttf","b06871f281fee6b241d60582ae9369b9"],["/static/fonts/fontawesome-webfont.fee66e7.woff","fee66e712a8a08eef5805a46892932ad"],["/static/images/icons/icon-128x128.png","e46e81cc7af7b4211d415e6ef8b35ca0"],["/static/images/icons/icon-144x144.png","d3157d073dc45e9845a045feeadf9208"],["/static/images/icons/icon-152x152.png","7c1512997966e8ff6045d1eaa42596cf"],["/static/images/icons/icon-192x192.png","f539533ae463ec1809e01548e98fec4b"],["/static/images/icons/icon-384x384.png","b2c872cacd0e78e9d1c4d33e6d40f088"],["/static/images/icons/icon-512x512.png","c51370ab250fe000abafc8cc271a2d00"],["/static/images/icons/icon-72x72.png","26141e3ccfc5ee37a9a8101894ebe07a"],["/static/images/icons/icon-96x96.png","c19180dcdde67a379177a99a76bcc945"],["/static/img/fontawesome-webfont.912ec66.svg","912ec66d7572ff821749319396470bde"],["/static/js/app.927af0144f62f58b23f7.js","ce9ab21cfa8156e9b57ba5b98eb56851"],["/static/js/manifest.ddc9f76beb1a96b6e9f7.js","1e010c056486a2477ab4b52ffbe02d27"],["/static/js/vendor.2466a447398800f4e57e.js","dc618b9ed4c3b2c19af14f0d3922f7d9"]];
```

As you can see, the googleapis.com urls are not present.

**Comment by goldhand** [comment]
`staticFileGlobs` need to point to file system paths. sw-precache will then add the matching files to the `precacheConfig`var.

**Comment by agnivade** [comment]
Ah yes, I had a feeling this would be the case. I will use local files and update the thread.

**Comment by agnivade** [comment]
Ok, works. Thanks.
