### ISSUE TITLE
Cannot read property 'toJson' of undefined

### ISSUE THREAD

**Issue by aclayton** [goldhand/sw-precache-webpack-plugin#80]
* [*] **I'm submitting a bug report**

**webpack version:**
webpack@^1.12.14

**sw-precache-webpack-plugin version**:
sw-precache-webpack-plugin@0.11.2

**Please tell us about your environment:**
OSX 10.11.6

**Browser:** [Chrome 58.0.3029.110]

**Current behavior:**

• After updating this package to latest npm release. 
• Previous to update would generate sw file, however that would crash in browser. (window undef.)
• Now crashes in gulp with following error:
`(node:14449) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'toJson' of undefined`

**Expected/desired behavior:**

*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with your:*

*  **Webpack configuration:**

`new SWPrecacheWebpackPlugin({
              cacheId: 'proto',
              filename: 'service-worker.js',
              staticFileGlobs: [
                `${__dirname}/dist/client/index.html`,
                `${__dirname}/dist/client/**/*`
              ],
              stripPrefix: path.join(__dirname, 'dist/client').replace(/\\/g,"/"),
              mergeStaticsConfig: true,
              importScripts: [
                {filename: 'vendor.[hash].js'},
                {filename: 'polyfills.[hash].js'},
                {filename: 'app.[hash].js'}
              ]
          })`

*  **Generated service worker (not minified):**
not produced

**Comment by goldhand** [comment]
Update to `0.11.3` @aclayton 

This was caused with the promisify function but is now fixed.

**Comment by aclayton** [comment]
Thanks! great work!
