### ISSUE TITLE
No Service Worker produced

### ISSUE THREAD

**Issue by aclayton** [goldhand/sw-precache-webpack-plugin#84]
## **BEFORE YOU SUBMIT** please read the following:

* [ ] **I'm submitting a bug report**

**webpack version:**
webpack@1.15.0

**sw-precache-webpack-plugin version**:
sw-precache-webpack-plugin@0.11.3

**Please tell us about your environment:**
OSX 10.11.6

**Browser:** Chrome 58.0.3029.

**Current behavior:**
No errors, but no service worker.

**Expected/desired behavior:**
a service worker file pre-caching assets

*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with your:*

*  **Webpack configuration:**
```
new SWPrecacheWebpackPlugin({
              cacheId: 'proto',
              filename: 'sw.js',
              staticFileGlobs: [
                `${__dirname}/dist/client/**/*`
              ],
              stripPrefix: path.join(__dirname, 'dist/client').replace(/\\/g,"/"),
              mergeStaticsConfig: true,
              importScripts: [
                {filename: 'vendor.[hash].js'},
                {filename: 'polyfills.[hash].js'},
                {filename: 'app.[hash].js'}
              ]
          })
```

*  **Generated service worker (not minified):**
None

**Comment by aclayton** [comment]
Dropped this plugin in preference of just using "sw-precache" and generating the service worker at the end of the gulp build process. Works well.

**Comment by goldhand** [comment]
Sorry you weren't able to get this to work for you. I am unable to reproduce this issue and think it is caused by something else in your webpack configuration.
