### ISSUE TITLE
Is it possible to "split" what service worker download ?

### ISSUE THREAD

**Issue by moimael** [goldhand/sw-precache-webpack-plugin#85]
## **BEFORE YOU SUBMIT** please read the following:

* [ ] **I'm submitting a bug report**
* [ ] **I'm submitting a feature request**
* [x] **I'm submitting a support request**

**webpack version:**
2.6.1

**sw-precache-webpack-plugin version**:
0.11.3

**Please tell us about your environment:**
Linux

**Browser:** [Phantom XX | Chrome XX | Firefox XX | IE XX | Safari XX | Other XX]

**Current behavior:**
Currently, I have a monorepo app which consist of several smaller apps, split by business domain. So my webpack config output several apps. The thing is, i'd like only the static file corresponding to each app to be downloaded, and not all of them.

**Expected/desired behavior:**
 For exemple if I go to my finance app, I only want to get finance js and css cached in the service worker, not static assets from other apps. Because right now, service worker tries to download 25MB of assets (all of the apps, more than a dozen).

A solution could be to output multiple service workers (1 per app). But is that even possible ?

**Comment by goldhand** [comment]
You can probably do that by specifying multiple SWPrecacheWebapckPlugin configs and specifying staticFileGlobs for each configuration

**Comment by moimael** [comment]
Yep that works perfectly fine :) Thank you very much !

**Comment by goldhand** [comment]
Awesome @moimael ! if you have time would you add your config to the readme in the examples section? It sounds like a neat use case I've not considered

**Comment by moimael** [comment]
Yes that's a good idea, i'll do a PR tomorrow !

**Comment by goldhand** [comment]
Thank you!

**Comment by moimael** [comment]
see #86
