### ISSUE TITLE
Failures: Manifest start_url is not cached by a Service Worker.

### ISSUE THREAD

**Issue by cescoferraro** [goldhand/sw-precache-webpack-plugin#91]
* [ ] **I'm submitting a bug report**
* [ ] **I'm submitting a feature request**
* [x] **I'm submitting a support request**

**webpack version:**
3

**sw-precache-webpack-plugin version**:
0.11.3

**Please tell us about your environment:**
OSX 10.12.5

**Browser:** [ Chrome Stable ]

**Current behavior:**
Service Worker does not include my start_url defined at manifest.json

![screen shot 2017-06-23 at 20 19 44](https://user-images.githubusercontent.com/6259987/27503303-569dd40e-5851-11e7-9aca-23d0443349b6.png)

**Expected/desired behavior:**
Include the start_url, but how?

*  **Manifest creation:**
using https://github.com/bbuhler/favicons-webpack-plugin

```js
    new FaviconsWebpackPlugin({
	prefix: 'icons/',
	logo: './shared/icon/favicon.png',
	config: {
	    appName: "acharh",
	    lang: "pt",
	    start_url: '/?pwa=true',
	    theme_color: '#00bfff'
	}
    }),
```

*  **manifest.json:**
[https://acharh.cescoferraro.xyz/icons/manifest.json](https://acharh.cescoferraro.xyz/icons/manifest.json)

```json
{
  "name": "acharh",
  "short_name": "acharh",
  "description": null,
  "dir": "auto",
  "lang": "pt",
  "display": "standalone",
  "orientation": "any",
  "start_url": "/?pwa=true",
  "background_color": "#fff",
  "theme_color": "#00bfff",
   ...
}
```

*  **swprecache config:**

```js
	    new SWPrecacheWebpackPlugin({
		staticFileGlobs: ['/?pwa=true'],
		staticFileGlobsIgnorePatterns: [/\.map$/], 
		mergeStaticsConfig: true
	    }),
```

**Comment by goldhand** [comment]
staticFlieGlobs should point to the file in your build directory, on your file system.  Is that where `/?pwa=true` is pointing to?

**Comment by cescoferraro** [comment]
You are right. But I have seen many websites at pwa.rocks that use the
query parameter to show the front end whenever it's a requests from a pwa.
Can I achieve this with this It's working with a /

**Comment by goldhand** [comment]
Sorry, sw-precache needs the file system path, not a url. You can reference the path to manifest.json but there's no way to specify a url then have it precached.

**Comment by tcatsl** [comment]
Solution I found if you're making a SPA: 
Use your index.html as the start_url and include
```html
<script>
var re = /index/g
if (re.test(window.location)) {
  window.location = '/'
}
</script>
```
in your index.html file.
