### ISSUE TITLE
webpack 3 support

### ISSUE THREAD

**Issue by gdborton** [goldhand/sw-precache-webpack-plugin#95]
I'm just curious when webpack 3 will be supported. I see that package.json has been updated to include webpack 3 in peer deps, but that a new release hasn't been cut yet. Is there additional work that needs to be done, anything I could help with?

## **BEFORE YOU SUBMIT** please read the following:

* [ ] **I'm submitting a bug report**
* [ ] **I'm submitting a feature request**
* [x] **I'm submitting a support request**

**webpack version:**
1.x / 2.x

**sw-precache-webpack-plugin version**:
0.9.x

**Please tell us about your environment:**
OSX 10.x

**Comment by goldhand** [comment]
Just testing! Meant to do that earlier.

**Comment by goldhand** [comment]
released in 0.11.4
